#!/bin/bash
#
# colorswirl
# shane tully (shane@shanetully.com)
# shanetully.com
# https://github.com/shanet/Adalight

### BEGIN INIT INFO
# Provides:          colorswirl
# Required-Start:    
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Runs colorswirl program
# Description:       Sends color info to Arduino for LED's
### END INIT INFO

BIN_PATH=/usr/sbin/
BINARY=colorswirl
ARGS="--color=multi --solid"
USER=root

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

start() {
        echo "Starting $BINARY..."
        start-stop-daemon --start -c $USER --exec $BIN_PATH$BINARY -- $ARGS
}

stop() {
        echo "Stopping $BINARY..."
        start-stop-daemon --stop --name $BINARY
}


# Make sure the binary is present
test -x $BIN_PATH$BINARY || {
   echo "$BINARY not installed";
   exit 1;
}

# Determine what to do
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status $BINARY
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0
